version: "3.9"
services:
  djl-sample-webapp:
    build: .
    image: djl-sample/springboot-webapp
#    network_mode: bridge
#    container_name: image_classification
    expose:
      - 8080
    ports:
      - 8088:8080
#    volumes:
#      - .:/var/tmp
#      - "//c/Users/firka/megalog-try-1/sample-logs:/sample-logs"
#    restart: unless-stopped